// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRI2aDUkPtRsSeRZD7MRZjwSC_rwNI_5E',
    appId: '1:308220562138:web:c2b71a86b0665660be33e3',
    messagingSenderId: '308220562138',
    projectId: 'flutternewpj',
    authDomain: 'flutternewpj.firebaseapp.com',
    storageBucket: 'flutternewpj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWnECUkkgfdkA8siPsNcuJ_E6Om86QCRM',
    appId: '1:308220562138:android:174c7b204ee2d78dbe33e3',
    messagingSenderId: '308220562138',
    projectId: 'flutternewpj',
    storageBucket: 'flutternewpj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VqIIduhfGT_MznlRtdDllsnxdd7oUF8',
    appId: '1:308220562138:ios:e1f6e94f0f0d0b14be33e3',
    messagingSenderId: '308220562138',
    projectId: 'flutternewpj',
    storageBucket: 'flutternewpj.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VqIIduhfGT_MznlRtdDllsnxdd7oUF8',
    appId: '1:308220562138:ios:27cd4d0aaae04574be33e3',
    messagingSenderId: '308220562138',
    projectId: 'flutternewpj',
    storageBucket: 'flutternewpj.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
